### ISSUE TITLE
Simple example of use `FullyShardedDataParallel`

### ISSUE THREAD

**Issue by sgugger** [facebookresearch/fairscale#423]
## ❓ Questions and Help

I may be doing something completely wrong, but I'm struggling to just get one forward pass through `FullyShardedDataParallel` without error. I've created a simple script:

```python
import os
from fairscale.nn.data_parallel import FullyShardedDataParallel as FullyShardedDDP
from transformers import BertModel
import torch
import torch.nn as nn
def main():
    torch.distributed.init_process_group(backend="nccl")
    # device = torch.device(int(os.environ.get("LOCAL_RANK", -1)))
    model = nn.Linear(200, 200).cuda()
    model = FullyShardedDDP(model)
    fake_inputs = torch.randn(32, 200).to(torch.device("cuda"))
    outputs = model(fake_inputs)

if __name__ == "__main__":
    main()
```
launched via
```bash
python -m torch.distributed.launch --nproc_per_node 2 --use_env path_to_script
```
and it fails with the following stack trace:
```
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "test_zero.py", line 20, in <module>
Traceback (most recent call last):
  File "test_zero.py", line 20, in <module>
    main()
  File "test_zero.py", line 13, in main
    model = FullyShardedDDP(model.cuda())
  File "/home/sgugger/git/fairscale/fairscale/nn/data_parallel/fully_sharded_data_parallel.py", line 161, in __init__
    main()
  File "test_zero.py", line 13, in main
    validate_process_group(compute_device, self.process_group)
  File "/home/sgugger/git/fairscale/fairscale/utils/parallel.py", line 41, in validate_process_group
    model = FullyShardedDDP(model.cuda())
  File "/home/sgugger/git/fairscale/fairscale/nn/data_parallel/fully_sharded_data_parallel.py", line 161, in __init__
    dist.all_gather(output, input_tensor, group=process_group)
  File "/home/sgugger/.pyenv/versions/base/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1434, in all_gather
    validate_process_group(compute_device, self.process_group)
  File "/home/sgugger/git/fairscale/fairscale/utils/parallel.py", line 41, in validate_process_group
    dist.all_gather(output, input_tensor, group=process_group)
  File "/home/sgugger/.pyenv/versions/base/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1434, in all_gather
    work = group.allgather([tensor_list], [tensor])
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, invalid usage, NCCL version 2.7.8
    work = group.allgather([tensor_list], [tensor])
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, invalid usage, NCCL version 2.7.8
Traceback (most recent call last):
  File "/home/sgugger/.pyenv/versions/3.7.9/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/sgugger/.pyenv/versions/3.7.9/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sgugger/.pyenv/versions/base/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/sgugger/.pyenv/versions/base/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/sgugger/.pyenv/versions/base/bin/python', '-u', 'test_zero.py']' returned non-zero exit status 1.
```

I'm using the `.cuda()` following what is done in the tests. Otherwise using the device (commented out in the script) and `.to(device)` also fails, with a different error:
```
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "test_zero.py", line 20, in <module>
    main()
  File "test_zero.py", line 16, in main
    outputs = model(fake_inputs)
  File "/home/sgugger/.pyenv/versions/base/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sgugger/git/fairscale/fairscale/nn/data_parallel/fully_sharded_data_parallel.py", line 612, in forward
    self._rebuild_full_params()
  File "/home/sgugger/.pyenv/versions/base/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home/sgugger/git/fairscale/fairscale/nn/data_parallel/fully_sharded_data_parallel.py", line 822, in _rebuild_full_params
    dist.all_gather(chunks, p.data, group=self.process_group)
  File "/home/sgugger/.pyenv/versions/base/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1434, in all_gather
    work = group.allgather([tensor_list], [tensor])
RuntimeError: Corresponding input/output tensors to scatter/gather must all reside on the same device
```

**Comment by myleott** [comment]
Ah, you need to set the default cuda device depending on the rank, then it works:
```
(...)
device = torch.device(int(os.environ.get("LOCAL_RANK", -1)))
torch.cuda.set_device(device)
(...)
```

**Comment by sgugger** [comment]
Indeed! To answer, you don't need to, no: for instance this script

```python
import os

import torch
import torch.nn as nn


def main():
    torch.distributed.init_process_group(backend="nccl")
    local_rank = int(os.environ.get("LOCAL_RANK", -1))
    device = torch.device(local_rank)
    model = nn.Linear(200, 200).to(device)
    model =  torch.nn.parallel.DistributedDataParallel(model, device_ids=[local_rank],  output_device=local_rank)
    fake_inputs = torch.randn(32, 200).to(device)
    outputs = model(fake_inputs)


if __name__ == "__main__":
    main()
```

will work.

Second question now is: does `FullyShardedDataParallel` support Embeddings layer? Changing the script to the following:
```python
import os
from fairscale.nn.data_parallel import FullyShardedDataParallel as FullyShardedDDP

from transformers import BertModel
import torch
import torch.nn as nn


def main():
    torch.distributed.init_process_group(backend="nccl")
    local_rank = int(os.environ.get("LOCAL_RANK", -1))
    device = torch.device(local_rank)
    torch.cuda.set_device(device)
    model = BertModel.from_pretrained("bert-base-cased").to(device)
    model = FullyShardedDDP(model)
    fake_inputs = torch.randint(0, 1000, (32, 200)).long().to(device)
    outputs = model(fake_inputs)


if __name__ == "__main__":
    main()
```

fails with the following stack trace:

```
*****************************************                                                                                                                                                                            Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.     *****************************************                                                                                                                                                                            Traceback (most recent call last):                                                                                                                                                                                     File "test_zero.py", line 21, in <module>                                                                                                                                                                          Traceback (most recent call last):                                                                                                                                                                                     File "test_zero.py", line 21, in <module>                                                                                                                                                                              main()                                                                                                                                                                                                             File "test_zero.py", line 17, in main                                                                                                                                                                                  outputs = model(fake_inputs)                                                                                                                                                                                       File "/home/sgugger/.pyenv/versions/base/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl                                                                                              main()                                                                                                                                                                                                             File "test_zero.py", line 17, in main                                                                                                                                                                                  outputs = model(fake_inputs)                                                                                                                                                                                       File "/home/sgugger/.pyenv/versions/base/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl                                                                                              result = self.forward(*input, **kwargs)                                                                                                                                                                            File "/home/sgugger/git/fairscale/fairscale/nn/data_parallel/fully_sharded_data_parallel.py", line 618, in forward                                                                                                     result = self.forward(*input, **kwargs)                                                                                                                                                                            File "/home/sgugger/git/fairscale/fairscale/nn/data_parallel/fully_sharded_data_parallel.py", line 618, in forward                                                                                                     outputs = self.module(*args, **kwargs)                                                                                                                                                                             File "/home/sgugger/.pyenv/versions/base/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl                                                                                              outputs = self.module(*args, **kwargs)                                                                                                                                                                             File "/home/sgugger/.pyenv/versions/base/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl                                                                                              result = self.forward(*input, **kwargs)                                                                                                                                                                            File "/home/sgugger/git/fairscale/fairscale/nn/misc/flatten_params_wrapper.py", line 153, in forward                                                                                                                   result = self.forward(*input, **kwargs)                                                                                                                                                                            File "/home/sgugger/git/fairscale/fairscale/nn/misc/flatten_params_wrapper.py", line 153, in forward                                                                                                                   return self.module(*inputs, **kwinputs)                                                                                                                                                                            File "/home/sgugger/.pyenv/versions/base/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl                                                                                              return self.module(*inputs, **kwinputs)                                                                                                                                                                            File "/home/sgugger/.pyenv/versions/base/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl                                                                                              result = self.forward(*input, **kwargs)                                                                                                                                                                            File "/home/sgugger/git/transformers/src/transformers/models/bert/modeling_bert.py", line 964, in forward                                                                                                              result = self.forward(*input, **kwargs)                                                                                                                                                                            File "/home/sgugger/git/transformers/src/transformers/models/bert/modeling_bert.py", line 964, in forward                                                                                                              past_key_values_length=past_key_values_length,                                                                                                                                                                     File "/home/sgugger/.pyenv/versions/base/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl                                                                                              past_key_values_length=past_key_values_length,                                                                                                                                                                     File "/home/sgugger/.pyenv/versions/base/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl                                                                                              result = self.forward(*input, **kwargs)                                                                                                                                                                            File "/home/sgugger/git/transformers/src/transformers/models/bert/modeling_bert.py", line 205, in forward                                                                                                              result = self.forward(*input, **kwargs)                                                                                                                                                                            File "/home/sgugger/git/transformers/src/transformers/models/bert/modeling_bert.py", line 205, in forward                                                                                                              position_embeddings = self.position_embeddings(position_ids)                                                                                                                                                       File "/home/sgugger/.pyenv/versions/base/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl                                                                                              position_embeddings = self.position_embeddings(position_ids)                                                                                                                                                       File "/home/sgugger/.pyenv/versions/base/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl                                                                                              result = self.forward(*input, **kwargs)                                                                                                                                                                            File "/home/sgugger/.pyenv/versions/base/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 126, in forward    result = self.forward(*input, **kwargs)                                                    File "/home/sgugger/.pyenv/versions/base/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 126, in forward    self.norm_type, self.scale_grad_by_freq, self.sparse)                                      File "/home/sgugger/.pyenv/versions/base/lib/python3.7/site-packages/torch/nn/functional.py", line 1852, in embedding                                                                                                  self.norm_type, self.scale_grad_by_freq, self.sparse)                                                                                                                                                              File "/home/sgugger/.pyenv/versions/base/lib/python3.7/site-packages/torch/nn/functional.py", line 1852, in embedding                                                                                                      return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)                                                                                                                                                                                                                                                                      RuntimeErrorRuntimeError: : Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.cuda.FloatTensor instead (while checking arguments for embedding)Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.cuda.FloatTensor instead (while checking arguments for embedding)                                                                                                                                                                                                                                                                                                                             Traceback (most recent call last):                                                                                                                                                                                     File "/home/sgugger/.pyenv/versions/3.7.9/lib/python3.7/runpy.py", line 193, in _run_module_as_main                                                                                                                    "__main__", mod_spec)                                                                                                                                                                                              File "/home/sgugger/.pyenv/versions/3.7.9/lib/python3.7/runpy.py", line 85, in _run_code                                                                                                                               exec(code, run_globals)                                                                                                                                                                                            File "/home/sgugger/.pyenv/versions/base/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>                                                                                               main()                                                                                                                                                                                                             File "/home/sgugger/.pyenv/versions/base/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main                                                                                                   cmd=cmd)                                                                                                                                                                                                         subprocess.CalledProcessError: Command '['/home/sgugger/.pyenv/versions/base/bin/python', '-u', 'test_zero.py']' returned non-zero exit status 1.  
```

**Comment by myleott** [comment]
Ah, probably position embedding buffers are getting overly aggressively cast to fp32. Should be a quick fix

**Comment by sgugger** [comment]
Confirming the fix works on my side, thank you so much! 

One unrelated question I had: from my understanding reading the tests, it doesn't matter if we place the model on the GPU before or after the sharding, though I imagine if the whole model does not fit on the GPU, it's better to do the split beforehand. However the optimizer absolutely needs to be created after the wrapping in `FullyShardedDataParallel`, is that correct? (This is another difference with regular DDP if that's the case, so might be good to highlight in the docs.)

I might have more questions as I continue integrating this cool feature into Transformers, thanks again for your help on this one :-)

**Comment by myleott** [comment]
> it doesn't matter if we place the model on the GPU before or after the sharding, though I imagine if the whole model does not fit on the GPU, it's better to do the split beforehand

Correct. In fact, for very large models (100B+) you usually won't even have CPU memory to initialize the entire model. In these cases you want to be wrapping each layer with FSDP as you initialize it (which will shard in place). Then once initialized on CPU you can move to CUDA.

> the optimizer absolutely needs to be created after the wrapping in FullyShardedDataParallel, is that correct? (This is another difference with regular DDP if that's the case, so might be good to highlight in the docs.)

Yes, great point, this is essential.

I'll leave this issue open to address a couple remaining things from this thread:
- [ ] better document that optimizer must be initialized after FSDP wrapper
- [ ] be more robust to mismatch between `torch.cuda.current_device` and model's device

**Comment by sgugger** [comment]
Thanks!

**Comment by myleott** [comment]
Did one, will track the other in https://github.com/facebookresearch/fairscale/issues/444
