### ISSUE TITLE
Model Offloading Issues

### ISSUE THREAD

**Issue by murnanedaniel** [facebookresearch/fairscale#804]
## ❓ Questions and Help

I have some issues with using and understanding model offloading.

1. The tutorial on model offloading (.../tutorials/offload_model.html) is not functioning out-of-the-box. Directly copying in this example on line `output = model(inputs)` gives the error:
```
Expected all tensors to be on the same device,
```
Presumably the fix is to use `output = offload_model(inputs)`? If so, this leads me to the second question:
2. How can we **see** the effect of model offloading? It would be extremely useful in the tutorial to show a quick benchmark of the model's GPU memory usage with and without model offloading. In particular, without checkpoint activation or FP16, to really zoom in on the behavior of offloading.
3. I have tried to benchmark this myself (assuming the fix `output = offload_model(inputs)`) and cannot see any improvement in memory usage. I am using `torch.cuda.max_memory_allocated()` as a proxy for when a GPU would give an OOM error, and running the example (with the model and data sizes scaled way up to see the effect) for offloaded and non-offloaded models shows no difference in `max_memory_allocated()`. 

Am I missing something obvious here? Am I using `offload_model` correctly?

**Comment by min-xu-ai** [comment]
cc @anj-s

**Comment by min-xu-ai** [comment]
Can you share a bit about your use case, @murnanedaniel? Do you have a single GPU and you want to training bigger model by offloading to the CPU memory? How big is your GPU and CPU memory? Do you have very fast CPU/GPU PCIe bandwidth?

**Comment by murnanedaniel** [comment]
Hi @min-xu-ai, thanks for the quick reply. My current setup is a single V100 (~16Gb) with NVLink interconnect to a Skylake with about 40Gb memory. This is on the [NERSC Cori HPC system](https://docs-dev.nersc.gov/cgpu/hardware/). The particular use-case is training GNNs on particle physics problems, which are non-trivial to shard across GPUs (due to message passing in the graph) - hence the single-GPU setup for now.
Some collaborators are training on this problem with the [large model offloading for TensorFlow, implemented by IBM](https://www.ibm.com/docs/en/wmlce/1.6.0?topic=gsmf-getting-started-tensorflow-large-model-support-tflms-v2). We have a predominantly Pytorch setup, so would like to replicate this behavior with FairScale. Is this the intended usage of the offloading system in FairScale? Before dropping the offloading into our GNN setup, I wanted to get a feel for the kind of scaling we could expect by starting with the fully connected linear layer example you give in the tutorial, but can't see how the memory requirement is being reduced. Hope you have some ideas! Thanks

**Comment by min-xu-ai** [comment]
I will let @anj-s provide more details. However, pcie 3 is not very fast and nvlink might be faster than it. In that case, multiple GPU might be faster than going to the CPU memory over pcie.

Do you have more details on the GNN, like the pytorch code of it or high level overview of it?

**Comment by murnanedaniel** [comment]
Training time is not a huge concern (within reason), but I see your point. We are working on a system that can split the graph data across GPUs for training the GNNs, but this is not working reliably yet. [Here is one of the models](https://github.com/HSF-reco-and-software-triggers/Tracking-ML-Exa.TrkX/blob/master/Pipelines/TrackML_Example/LightningModules/GNN/Models/agnn.py) we are using, with the training code (as a Lightning module) [here](https://github.com/HSF-reco-and-software-triggers/Tracking-ML-Exa.TrkX/blob/master/Pipelines/TrackML_Example/LightningModules/GNN/gnn_base.py). 
We have successfully implemented activation [checkpointing in this model](https://github.com/HSF-reco-and-software-triggers/Tracking-ML-Exa.TrkX/blob/master/Pipelines/TrackML_Example/LightningModules/GNN/Models/checkpoint_agnn.py), and seen ~4x memory reduction. I'm hoping we can stack the benefits of offloading on top of this.

**Comment by anj-s** [comment]
> ## ❓ Questions and Help
> I have some issues with using and understanding model offloading.
> 
> 1. The tutorial on model offloading (.../tutorials/offload_model.html) is not functioning out-of-the-box. Directly copying in this example on line `output = model(inputs)` gives the error:
> 
> ```
> Expected all tensors to be on the same device, ... etc.
> ```
> 
> Presumably the fix is to use `output = offload_model(inputs)`? If so, this leads me to the second question:

Thanks for bringing this to our attention! you are absolutely right. Opened a [PR](https://github.com/facebookresearch/fairscale/pull/806) to fix this.

> 1. How can we **see** the effect of model offloading? It would be extremely useful in the tutorial to show a quick benchmark of the model's GPU memory usage with and without model offloading. In particular, without checkpoint activation or FP16, to really zoom in on the behavior of offloading.

You can use the offload benchmark script and [toggle fp16 and activation checkpointing](https://github.com/facebookresearch/fairscale/blob/ssd_offload/benchmarks/experimental/offload.py#L421) to compare throughput and peak memory allocated. The other thing you can try is to use a memory profiler:
1. pip install the memory_profiler
2. mprof run --multiprocess -C -T 0.01 python <your file>
--multiprocess to show each individual child process on the graph, -C to show the memory usage of all child processes combined, and -T to set polling interval
3. mprof plot -o mprof.png -t "<Title>"

This should give you CPU and GPU graphs to compare with. 

> 2. I have tried to benchmark this myself (assuming the fix `output = offload_model(inputs)`) and cannot see any improvement in memory usage. I am using `torch.cuda.max_memory_allocated()` as a proxy for when a GPU would give an OOM error, and running the example (with the model and data sizes scaled way up to see the effect) for offloaded and non-offloaded models shows no difference in `max_memory_allocated()`.
> 
> Am I missing something obvious here? Am I using `OffloadModel` correctly?

The first thing I noticed is that your model is not a nn.Sequential model. Is that right? This might mean that the model is not sharded. Can you confirm this by printing out offload_model._model? There are a couple of options if your model is not nn.Sequential:
1. Convert it to a nn.Sequential model
2. Use experimental [auto_shard.py](https://github.com/facebookresearch/fairscale/blob/15568668b0c97173def2eaf489c1201020ff2d4e/fairscale/experimental/nn/auto_shard.py#L115) script to shard your model. This should work if you don't have conditionals in your forward function.  Here is a [test](https://github.com/facebookresearch/fairscale/blob/15568668b0c97173def2eaf489c1201020ff2d4e/tests/experimental/nn/test_auto_shard.py#L88) that demonstrates usage.
3. Use torch.fx similar to what is present in auto_shard.py but shard at a module level. I've been meaning to do this since I think it might be easier than sharding at a node level.

**Comment by murnanedaniel** [comment]
@anj-s Thanks very much for this thoughtful reply (and apologies for the delay of my own).

I've been doing some tests to understand better how to apply the Fairscale offloading to our GNN case. I have converted our recurrent GNN to a simple set of nn.Sequential models, and have been working from the simplest possible case towards these more sophisticated GNN models. I believe I have found a culprit in why our case is not working out-of-the-box. I think it has to do with us handling nodes and edges as a kind of minibatch, and this not working as expected.

Consider a simple "GNN" (just a binary classifier for "edges"):
```
num_graphs = 10
num_input = 3
num_edges = 100000
num_outputs = 1

num_hidden =  1024
num_layers =  10

edges = torch.rand(num_graphs, num_edges, num_input)
truth = torch.round(torch.rand(num_graphs, num_edges))
graph_data = torch.utils.data.TensorDataset(edges, truth)
dataloader = DataLoader(graph_data, batch_size=1)

model = torch.nn.Sequential(
    torch.nn.Linear(num_input, num_hidden),
    *([torch.nn.Linear(num_hidden, num_hidden) for _ in range(num_layers)]),
    torch.nn.Linear(num_hidden, num_outputs),
)
```

Training this with 
```
model = model.to(device)
criterion = torch.nn.BCEWithLogitsLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)

model.train()
for batch_edges, batch_truth in dataloader:
    batch_edges, batch_truth = batch_edges.to("cuda").squeeze(0), batch_truth.to("cuda").squeeze(0)

    optimizer.zero_grad()
    output = model(batch_edges)
    loss = criterion(output.squeeze(), target=batch_truth)
    loss.backward()
    optimizer.step()
```
This takes about 4.7Gb of `max_memory_allocated`.  Adapting the model to 
```
model = OffloadModel(
    model=model,
    device=torch.device("cuda"),
    offload_device=torch.device("cpu"),
    num_slices=num_layers,
    checkpoint_activation=False,
    num_microbatches=1,
)
```
actually takes up a little more memory (about 5.1Gb), while using sequential checkpointing (from `torch.utils`) reduces memory usage to about 1.6Gb. On the other hand, using only one edge (`num_edges=1`) but a much wider network (e.g. `num_hidden = 5096`) does indeed show a benefit from offloading (1.9Gb -> 1.6Gb).

Shouldn't we be able to see a reduction in memory usage from offloading even in this toy model (naively a reduction proportional to the number of layers)? Or is this getting washed out due to the large "batch" size (where batch here means a single whole graph of edges)? Can you think of a way around this?

**Comment by anj-s** [comment]
@murnanedaniel Apologies for the late reply! Can you isolate the effects of a large "batch" size by using a small number of edges (=1) with the same deep network? Does that change the memory allocation? 
The other question I did have is how are you slicing your network? I see that you set num_slices=num_layers and the default value is 3. Can you slice your model with finer granularity?
